#!/bin/sh

# autostart entries

echo $DISPLAY > ~/.DISPLAY # store $DISPLAY for graphical crontab programs
lxpanel &
twmnd & # for libnotify

# open terminal if not already open
pidof "${WMII_TERM:-konsole}" || "${WMII_TERM:-konsole}" &

# stuff to do after a system tray starts

until pidof lxpanel >/dev/null; do
  sleep 1
done

# JACK
# delay to show systray icon
{ sleep 3; qjackctl --start; } &

# Audio mixer panel
pidof kmix >/dev/null || kmix --keepvisibility &

# Wi-Fi control
pidof wpa_gui >/dev/null || { sleep 3; wpa_gui -t } &
